name: DSA_DART
description: A simple Dart project for file handling and HTTP requests.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
